config/routes.rb
Rails.application.routes.draw do

  #RUTAS DE LA TABLA Tiendas
  get '/tiendas', to: 'tiendas#index'
  get '/tiendas/new', to: 'tienda#new'
  post '/tiendas', to: 'tiendas#create'
  get '/tienda/:id', to: 'tiendas#show', as: 'tienda'
  get '/tiendas/:id/edit', to: 'tiendas#edit', as: 'edit_tienda'
  patch '/tienda/:id', to: 'tiendas#update'
  put '/tienda/:id', to: 'tiendas#update'
  delete '/tienda/:id', to: 'tiendas#delete'

  #RUTAS DE LA TABLA PRODUCTOS
  get '/productos', to: 'productos#index'
  get '/productos/new', to: 'producto#new'
  post '/productos', to: 'productos#create'
  get '/producto/:id', to: 'productos#show', as: 'producto'
  get '/producto/:id/edit', to: 'productos#edit', as: 'edit_producto'
  patch '/producto/:id', to: 'productos#update'
  put '/producto/:id', to: 'productos#update'
  delete '/producto/:id', to: 'productos#delete'

  #RUTAS DE LA TABLA CATEGORIA
  get '/categorias', to: 'categorias#index'
  get '/categorias/new', to: 'categoria#new'
  post '/categorias', to: 'categorias#create'
  get '/categoria/:id', to: 'categorias#show', as: 'categoria'
  get '/categoria/:id/edit', to: 'categorias#edit', as: 'edit_categoria'
  patch '/categoria/:id', to: 'categorias#update'
  put '/categoria/:id', to: 'categorias#update'
  delete '/categoria/:id', to: 'categorias#delete'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/models/tienda.rb
class Tienda < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  def index
    @categorias = Categoria.all
  end

  def new
    @categorias = Categoria.new
  end

  def create
    @categorias = Categoria.new(categoria_params)
      if @categorias.save
        redirect_to categorias_path
      else
        render :new
      end
  end

  def edit
    @categorias = Categoria.find(params[:id])
  end

  def update
    @categorias = Categoria.find(params[:id])
      if @categorias.update(categoria_params)
        redirect_to categorias_path
      else
        render :edit
      end
  end

  def delete
    @categorias = Categoria.find(params[:id])
    @categorias.destroy
    redirect_to categorias_path
  end

  private
    def categoria_params
      params.require(:categoria).permit(:id_categoria, :nombre_categoria, :nombre_producto)
    end
 end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController

    def index
      @productos = Producto.all
    end

    def new
      @productos = Producto.new
    end

    def create
      @productos = Producto.new(producto_params)
        if @tiendas.save
          redirect_to productos_path
        else
          render :new
        end
    end

    def edit
      @productos = Producto.find(params[:id])
    end

    def update
      @productos = Producto.find(params[:id])
        if @productos.update(producto_params)
          redirect_to productos_path
        else
          render :edit
        end
    end

    def delete
      @productos = Producto.find(params[:id])
      @productos.destroy
      redirect_to productos_path
    end

    private
      def producto_params
        params.require(:producto).permit(:id_producto, :nombre_producto, :descripcion_producto, :precio,
        :nombre_categoria, :nombre_tienda)
      end
   end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController

  def index
    @tiendas = Tienda.all
  end

  def new
    @tiendas = Tienda.new
  end

  def create
    @tiendas = Tienda.new(tienda_params)
      if @tiendas.save
        redirect_to tiendas_path
      else
        render :new
      end
  end

  def edit
    @tiendas = Tienda.find(params[:id])
  end

  def update
    @tiendas = Tienda.find(params[:id])
      if @tiendas.update(tienda_params)
        redirect_to tiendas_path
      else
        render :edit
      end
  end

  def delete
    @tiendas = Tienda.find(params[:id])
    @tiendas.destroy
    redirect_to tiendas_path
  end

  private
    def tienda_params
      params.require(:tienda).permit(:id_tienda, :nombre_tienda, :descripcion_tienda, :ciudad,
      :pais, :nombre_producto)
    end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/views/categoria/edit.html.erb
<%= form_for @categoria do |f| %>
  <div>
    <%= f.label :id_categoria %>
    <%= f.number_field :id_categoria %>
  </div>
  <div>
    <%= f.label :nombre_categoria %>
    <%= f.text_area :nombre_categoria %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.text_area :nombre_producto %>
  </div>

<% end %>

app/views/categoria/index.html.erb
<h1>Categoria</h1>
<%= link_to "Crear Categorias", categoria_new_path %>
<table>
  <tr>
    <thead>
      <th>Id</th>
      <th>Categoria</th>
      <th>Producto</th>
    </thead>
  </tr>
    <% @categorias.each do |categoria| %>
  <tr>
    <td><%= categoria.id_categoria %></td>
    <td><%= categoria.nombre_categoria %></td>
    <td><%= categoria.nombre_producto %></td>

    <td>
      <%= link_to "Editar", edit_categoria_path(categoria) %>
      <%= link_to "Eliminar", categoria, method: :delete, data: { confirm: "Deseas eliminar la categoria?"} %>
    </td>
  </tr>
    <% end %>
</table>

app/views/categoria/new.html.erb
<%= form_for @categoria do |f| %>
  <div>
    <%= f.label :id_categoria %>
    <%= f.number_field :id_categoria %>
  </div>
  <div>
    <%= f.label :nombre_categoria %>
    <%= f.text_area :nombre_categoria %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.text_area :nombre_producto %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubywebtestjustclick</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productos/edit.html.erb
<%= form_for @producto do |f| %>
  <div>
    <%= f.label :id_producto %>
    <%= f.number_field :id_producto %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.text_area :nombre_producto %>
  </div>
  <div>
    <%= f.label :descripcion_producto %>
    <%= f.text_field :descripcion_producto %>
  </div>
  <div>
    <%= f.label :precio %>
    <%= f.number_field :precio %>
  </div>
  <div>
    <%= f.label :nombre_tienda %>
    <%= f.text_field :nombre_tienda %>
  </div>
  <div>
    <%= f.label :nombre_categoria %>
    <%= f.text_field :nombre_categoria %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/index.html.erb
<h1>Productos</h1>
<%= link_to "Crear Productos", producto_new_path %>
<table>
  <tr>
    <thead>
      <th>Id</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th>Tienda</th>
      <th>Categoria</th>
    </thead>
  </tr>
    <% @productos.each do |producto| %>
  <tr>
    <td><%= producto.id_producto %></td>
    <td><%= producto.nombre_producto %></td>
    <td><%= producto.descripcion %></td>
    <td><%= producto.precio %></td>
    <td><%= producto.nombre_tienda %></td>
    <td><%= producto.nombre_categoria %></td>

    <td>
      <%= link_to "Editar", edit_producto_path(tienda) %>
      <%= link_to "Eliminar", producto, method: :delete, data: { confirm: "Deseas eliminar el producto?"} %>
    </td>
  </tr>
    <% end %>
</table>

app/views/productos/new.html.erb
<%= form_for @producto do |f| %>
  <div>
    <%= f.label :id_producto %>
    <%= f.number_field :id_producto %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.text_area :nombre_producto %>
  </div>
  <div>
    <%= f.label :descripcion_producto %>
    <%= f.text_field :descripcion_producto %>
  </div>
  <div>
    <%= f.label :precio %>
    <%= f.number_field :precio %>
  </div>
  <div>
    <%= f.label :nombre_tienda %>
    <%= f.text_field :nombre_tienda %>
  </div>
  <div>
    <%= f.label :nombre_categoria %>
    <%= f.text_field :nombre_categoria %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/tiendas/edit.html.erb
<%= form_for @tienda do |f| %>
  <div>
    <%= f.label :id_tienda %>
    <%= f.number_field :id_tienda %>
  </div>
  <div>
    <%= f.label :nombre_tienda %>
    <%= f.text_area :nombre_tienda %>
  </div>
  <div>
    <%= f.label :descripcion_tienda %>
    <%= f.text_field :descripcion_tienda %>
  </div>
  <div>
    <%= f.label :ciudad %>
    <%= f.text_area :ciudad %>
  </div>
  <div>
    <%= f.label :pais %>
    <%= f.text_area :pais %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.number_area :nombre_producto %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/tiendas/index.html.erb
<h1>Tiendas</h1>
<%= link_to "Crear Tiendas", tienda_new_path %>
<table>
  <tr>
    <thead>
      <th>Id</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Producto</th>
    </thead>
  </tr>
    <% @tiendas.each do |tienda| %>
  <tr>
    <td><%= tienda.id_tienda %></td>
    <td><%= tienda.nombre_tienda %></td>
    <td><%= tienda.descripcion %></td>
    <td><%= tienda.ciudad %></td>
    <td><%= tienda.pais %></td>
    <td><%= tienda.nombre_producto %></td>

    <td>
      <%= link_to "Editar", edit_tienda_path(tienda) %>
      <%= link_to "Eliminar", tienda, method: :delete, data: { confirm: "Deseas eliminar la informacion de la tabla tiendas?"} %>
    </td>
  </tr>
    <% end %>
</table>

app/views/tiendas/new.html.erb
<%= form_for @tienda do |f| %>
  <div>
    <%= f.label :id_tienda %>
    <%= f.number_field :id_tienda %>
  </div>
  <div>
    <%= f.label :nombre_tienda %>
    <%= f.text_area :nombre_tienda %>
  </div>
  <div>
    <%= f.label :descripcion_tienda %>
    <%= f.text_field :descripcion_tienda %>
  </div>
  <div>
    <%= f.label :ciudad %>
    <%= f.text_area :ciudad %>
  </div>
  <div>
    <%= f.label :pais %>
    <%= f.text_area :pais %>
  </div>
  <div>
    <%= f.label :nombre_producto %>
    <%= f.number_area :nombre_producto %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>